---
title: "L00 Setup"
subtitle: "Data Science 1 with R (STAT 301-1)"
author: "Yecheng Wang"
date: today

format:
  html:
    toc: true
    embed-resources: true
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji 
---


::: {.callout-tip icon=false}

## Github Repo Link

[https://github.com/stat301-1-2023-fall/L00-setup-yechengwang.git](https://github.com/stat301-1-2023-fall/L00-setup-yechengwang.git)

:::

::: {.callout-warning}
This is a template file and may not contain everything seen in the instructions html (`L00_setup.html`). For example, images or graphs are not usually included in the template. **Rely on the instructions html file for directions, not the template file.**
:::

## Overview

1.  Ensure software for this course is properly installed and functional
2.  Develop and follow a proper workflow that is generalizable
3.  Explore basics of RStudio and quarto
4.  Introduce useful tips and tricks when working in RStudio

**Don't worry if you cannot do everything by yourself.** You are just getting started and the learning curve is steep, but remember that the instructional team and your classmates will be there to provide support. Persevere and put forth an honest effort and this course will payoff.

::: callout-tip
All packages should always be loaded at the TOP of the document.
:::


## Tasks

Complete the following tasks. For each task you'll need to simply **indicate that you have completed the task**.

### Task 1

Download and install [R Software](https://cran.rstudio.com/).

COMPLETED

### Task 2

1.  Download and install [RStudio](https://www.rstudio.com/products/rstudio/download4/).
2.  Open RStudio and ensure it and R have been properly installed.
3.  Go to **Tools** \> **Global Options** and change the two indicated settings below and click **Apply**. Your other options are likely different than what is pictured. This is okay and we suggest you leave them as is until you become more familiar with RStudio.

COMPLETED

### Task 3

Install the following packages:

-   `tidyverse`
-   `skimr`
-   `janitor`
-   `nycflights13`
-   `gapminder`
-   `Lahman`
-   `devtools`
-   `tutorial.helpers`
-   `r4ds.tutorials`

COMPLETED

### Task 4

Create a [GitHub](http://www.github.com/) account.

Install git and connect to RStudio. See textbook [Happy Git and GitHub for the useR](https://happygitwithr.com/) Chapters 1 - 9.

COMPLETED

### Task 5

Since organization is essential for any data science project or work, we should begin by setting up an organizational structure for this course and its contents.

0.  Setup a directory/folder on your laptop that will contain all your materials and work for this course. You may already have one setup and named. We will setup this directory and call it `stat301-1`. Where this is located on your laptop is completely up to you.

1.  Within `stat301-1/`, place a copy of the course syllabus for future reference. We also will create a new sub-directory that will contain all labs for this course. For ease let us call it `labs`. So now we have `stat301-1/labs/`.

2.  Open RStudio and create a "New Project" using "Version Control" -> "Git"

3.  Copy the URL from GitHub. Browse so that you place this project within the `stat301-1/labs/` folder that you created.

4.  Rename `template_L00.qmd` to your `Lastname_Firstname_L00.qmd`

5.  Render the file with `Cmd/Ctrl + Shift + K` or click the **Render button**.

COMPLETED

### Task 6 (optional)

It is always handy to have a versatile text editor and I would suggest downloading [Sublime Text](https://www.sublimetext.com/). It is free to use.

COMPLETED

## Exercises

### Exercise 1

Suppose a random variable $X$ has finite variance, then as we take larger random samples (i.e. as $n$ increases) we have that $$\bar{X} \sim N\left(\mu_{\bar{X}}=\mu_X, \sigma^2_{\bar{X}} = \frac{\sigma_X^2}{n}\right)$$ This is an informal statement of which important statistical theorem?


::: {.callout-tip icon="false"}
## Solution

Central Limit Theorem

:::

::: {.callout-tip icon=false}

If the mathematical notation in Exercise 1 does not compile correctly you will need to download and install either [MikTex](https://miktex.org/download) for windows machines or [MacTex](https://tug.org/mactex/mactex-download.html) for Mac OS machines.

Even if the equation in Exercise 1 does compile, you may need to download MikTex/MacTex to compile pdfs. We highly suggest being able to compile pdf's, but it is not a requirement for undergraduates in this course.

**Graduate Students are required to be able to compile pdf's.** It is more for your own good going forward, than being directly beneficial for this course. Please submit a complied pdf of this assignment in addition to the standard html file.

:::

### Exercise 2

Create a code chunk and assign the value 5 to `x` and the value 3 to `y`. 
Then print `x * y`.

::: {.callout-tip icon="false"}
## Solution

```{r}
x <- 5
y <- 3

x * y
```


:::

## Reminders

::: {.callout-tip icon=false}
- Render often!

- Make sure you commit and push all changes to GitHub! Do this EVERY TIME you are done working. NOT just before you are ready to submit to Canvas. You will often have MANY commits... think of each commit as a save spot.

- Upload your .html to Canvas. 
:::
